# Generated by Django 5.1.5 on 2025-03-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('course_name', models.CharField(max_length=200)),
            ],
        ),
    ]
