# Generated by Django 5.1.5 on 2025-03-09 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappunv', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
    ]
