# Generated by Django 5.1.5 on 2025-03-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappunv', '0002_rename_courses_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='WiFiFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.CharField(max_length=100)),
                ('rssi_min', models.IntegerField()),
                ('rssi_max', models.IntegerField()),
                ('location_name', models.CharField(max_length=200)),
            ],
        ),
    ]
