# Generated by Django 5.1.5 on 2025-03-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappunv', '0003_wififingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='wififingerprint',
            name='bssid',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
