# Generated by Django 5.1.5 on 2025-03-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappunv', '0004_wififingerprint_bssid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wififingerprint',
            name='bssid',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
